# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OurFingering' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OurFingering
  pod "Floaty", "~> 4.0.0"
  pod 'AWSMobileClient', '~> 2.6.13'

  target 'OurFingeringTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OurFingeringUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
